###
POST http://localhost:8080/api/v1/product/new-product
Content-Type: application/json

{
  "productName": "Iron",
  "description": "best noodles",
  "price": 13.0,
  "categoryName": "Electronics"
}

###
GET http://localhost:8080/api/v1/product/all

###
POST http://localhost:8080/api/v1/category/new-category
Content-Type: application/json

{
  "categoryName": "Electronics"
}

###

GET http://localhost:8080/api/v1/category/all