spring:
  application:
    name: backend
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/productDB
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
